# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24a5279870102bb7d5870769a5b296b4d8ff1b60fa9d383c44f12a167422a23b40f0c5e019a57ac0d37ab64a87748f73fc22c755bca8e714ecf55b1c00ac0a19
  mailchimp_api_key: b5e23bbc4f7ce5f67e42e439020e602a-us3
  mailchimp_list_id: 2342f3f46a
  mailchimp_crowdfunding_list: 37249bb85b
  app_host: http://d0b205e3.ngrok.io
  paypal_host: https://www.sandbox.paypal.com
  merchant_account: johncarter_merchant@gmail.com
  buyer_account: johncarter_buyer@gmail.com
  plaid_client_id: 588ab977bdc6a44583218935 
  plaid_secret: 6bb4f5898e1d0e88c32500dd46180e
  plaid_public_key: ac467520df2aba613144e341d4792e
  hello_sign_api_key: 1b4eef41f9aadb3ab788dec65149d45dcc5f89a86dec6072be29ae65caef6683
  hello_sign_client_id: ef79488ccabae86166e892ee6feefe2a
test:
  secret_key_base: 49a15bb72cd4249df63ece6f5c1287a6e07e1c0f6c5566f27e6153a6c4765b3c305cd7de421daad8eabb898020b2c42861fc13592ec46d2bcd2ee437a90172c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mailchimp_api_key: b5e23bbc4f7ce5f67e42e439020e602a-us3
  mailchimp_list_id: 2342f3f46a
  mailchimp_crowdfunding_list: 37249bb85b


# Access Key ID:
# AKIAJWDE6UJS56MXQYPQ
# Secret Access Key:
# 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
